from __future__ import annotations

import hashlib
import json
import re

from app.llm.base import LLMClient, LLMResponse


class MockLLMClient(LLMClient):
    """
    Deterministic fake LLM for dev/testing without a Grok key.

    Heuristically pulls obvious fields (email, phone, name from headers, common
    skill keywords) out of the input text so the parser pipeline returns
    realistic-shaped data end-to-end.
    """

    backend_name = "mock"
    model = "mock-resume-parser-v1"

    _EMAIL_RE = re.compile(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}")
    _PHONE_RE = re.compile(r"(\+?\d[\d\s\-().]{7,}\d)")
    _COMMON_SKILLS = [
        "python", "java", "javascript", "typescript", "go", "rust", "c++", "c#",
        "fastapi", "django", "flask", "spring", "node.js", "react", "next.js",
        "vue", "angular", "postgresql", "mysql", "mongodb", "redis", "kafka",
        "celery", "airflow", "spark", "hadoop", "aws", "gcp", "azure", "kubernetes",
        "docker", "terraform", "ansible", "git", "linux", "tensorflow", "pytorch",
        "scikit-learn", "xgboost", "pandas", "numpy", "ml", "nlp", "llm", "sql",
        "graphql", "rest", "grpc", "pgvector", "elasticsearch", "snowflake", "dbt",
    ]

    def complete_json(self, system: str, user: str) -> LLMResponse:
        # `user` payload is the resume text; everything else came in `system`.
        text = user
        lower = text.lower()

        email_match = self._EMAIL_RE.search(text)
        phone_match = self._PHONE_RE.search(text)

        # Naive name guess: first non-empty line that isn't an email/phone/header.
        full_name = "Unknown Candidate"
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped or "@" in stripped:
                continue
            if any(stripped.lower().startswith(h) for h in ("resume", "curriculum", "cv")):
                continue
            if len(stripped) <= 80 and not stripped.endswith("."):
                full_name = stripped
                break

        skills = sorted({s for s in self._COMMON_SKILLS if s in lower})

        # Deterministic but realistic-looking placeholder experience.
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
        years = int(digest[0:2], 16) % 12 + 1

        parsed = {
            "full_name": full_name,
            "email": email_match.group(0) if email_match else None,
            "phone": phone_match.group(0).strip() if phone_match else None,
            "headline": (skills[0].capitalize() + " engineer") if skills else None,
            "location": None,
            "skills": skills,
            "experience": [
                {
                    "company": "ExampleCorp",
                    "title": "Senior Engineer",
                    "start_date": "2020-01-01",
                    "end_date": None,
                    "is_current": True,
                    "description": f"Auto-generated by mock LLM. Detected {years}y of experience hint.",
                }
            ],
            "education": [
                {
                    "institution": "Example University",
                    "degree": "B.Tech",
                    "field": "Computer Science",
                    "start_date": "2014-08-01",
                    "end_date": "2018-05-31",
                    "grade": None,
                }
            ],
            "certifications": [],
            "languages": [{"language": "English", "proficiency": "fluent"}],
        }
        return LLMResponse(text=json.dumps(parsed), model=self.model, backend=self.backend_name)
